#ifndef _CONFIG_VARIABLES_H_
#define _CONFIG_VARIABLES_H_

double MIN_FREQUENCY;
double MAX_FREQUENCY;
double MIN_ABSOLUTE_MAGNITUDE;
double MAX_MAGNITUDE_GAP;
double MAX_ADJACENT_MAGNITUDE_GAP;

#endif /* _CONFIG_VARIABLES_H_ */
